name: sta_test_website_app
description: Flutter wrapper app for STA Test Website.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/www/public/
    - assets/www/src/
    - assets/www/public/assets/asian-book/
    - assets/www/public/assets/asian-book/
